version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: simufrag_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

# After docker-compose up -d
# cd .\init-scripts\
# docker cp scripts.sql simufrag_db:/tmp/scripts.sql
# docker exec -it simufrag_db psql -U user -d frag_0 -f /tmp/scripts.sql
# docker exec -it simufrag_db psql -U user -d frag_1 -f /tmp/scripts.sql
# docker exec -it simufrag_db psql -U user -d frag_2 -f /tmp/scripts.sql